import { SlashCommandBuilder, EmbedBuilder } from 'discord.js';

// 🔮 Safely grabs your free Google key from your host dashboard
const GEMINI_API_KEY = process.env.GEMINI_API_KEY; 

export default {
    data: new SlashCommandBuilder()
        .setName('8ball')
        .setDescription('Ask the magic 8-ball a question and get a custom AI answer')
        .addStringOption(option =>
            option.setName('question')
                .setDescription('The question you want to ask the 8-ball')
                .setRequired(true)
        ),
    category: "Fun",

    async execute(interaction) {
        const question = interaction.options.getString('question');

        // Defer the reply immediately since AI generation takes a brief moment
        await interaction.deferReply();

        let finalAnswer = "";
        let errorOccurred = false;

        // Check if the Gemini environment variable is actually present
        if (!GEMINI_API_KEY) {
            finalAnswer = "⚠️ **Error:** The `GEMINI_API_KEY` variable is missing from your host dashboard panel.";
            errorOccurred = true;
        } else {
            try {
                // Connect directly to Google Gemini's API endpoint
                const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        contents: [{
                            parts: [{
                                text: `Context: You are a hilarious, witty Magic 8-Ball inside a competitive Minecraft SMP Discord server named Flow SMP. 
                                Task: Read the user's question and give a genuinely funny, smart, or accurate answer to it. Deliver the answer using modern gaming community slang or casual chat slang. Keep it short (1 to 2 sentences max). Do not include any filler text.
                                
                                User Question: "${question}"`
                            }]
                        }],
                        generationConfig: {
                            maxOutputTokens: 100,
                            temperature: 0.85
                        }
                    })
                });

                if (!response.ok) {
                    throw new Error(`Google API responded with status ${response.status}`);
                }

                const data = await response.json();
                
                // Safely extract the text generated by Google Gemini
                if (data.candidates && data.candidates[0]?.content?.parts[0]?.text) {
                    finalAnswer = data.candidates[0].content.parts[0].text.trim();
                } else {
                    throw new Error("Invalid response structure from Google Gemini API.");
                }
            } catch (error) {
                console.error('8Ball Gemini System Error:', error);
                finalAnswer = "⚠️ **Error:** Failed to connect to the Google Gemini Engine. Check your host dashboard logs to see the error details.";
                errorOccurred = true;
            }
        }

        // Build the updated embed display response
        const embed = new EmbedBuilder()
            .setTitle('🔮 The Custom 8-Ball')
            .setColor(errorOccurred ? '#FF3333' : '#00FFCC') // Red for errors, Cyan for success
            .addFields(
                { name: '❓ Your Question', value: `\`\`\`${question}\`\`\``, inline: false },
                { name: '🎱 The Answer', value: errorOccurred ? finalAnswer : `> **${finalAnswer}**`, inline: false }
            )
            .setFooter({ 
                text: `Asked by ${interaction.user.username} • Mode: ♊ 100% Google Gemini AI` 
            })
            .setTimestamp();

        // Send the completed embed back to the channel
        await interaction.editReply({ embeds: [embed] });
    }
};
